services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: possystemapi:dev
    container_name: nova-pos-api
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ApplicationDbContext=Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=pos-system;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False


